name: Karbala Direct Stream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start Live Stream
        run: |
          # سحب البث المباشر الخام (بعيداً عن اليوتيوب) وتوجيهه لقناتك
          ffmpeg -re -i "https://shrine.karbala.tv/live/st1/playlist.m3u8" \
          -c:v libx264 -preset ultrafast -b:v 450k -maxrate 450k -bufsize 900k \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/q12g-s6wc-0y03-0ua5-6e6p"
          
